# Generated by Django 2.2 on 2020-03-16 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COLOR',
            fields=[
                ('COLOR_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('STATE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TEAM',
            fields=[
                ('TEAM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('WINS', models.IntegerField()),
                ('LOSSES', models.IntegerField()),
                ('COLOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormApp.COLOR')),
                ('STATE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormApp.STATE')),
            ],
        ),
        migrations.CreateModel(
            name='PLAYER',
            fields=[
                ('PLAYER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('UNIFORM_NUM', models.IntegerField()),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('MPG', models.IntegerField()),
                ('PPG', models.IntegerField()),
                ('RPG', models.IntegerField()),
                ('APG', models.IntegerField()),
                ('SPG', models.FloatField()),
                ('BPG', models.FloatField()),
                ('TEAM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormApp.TEAM')),
            ],
        ),
    ]
