# Generated by Django 2.2 on 2020-03-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ormApp', '0002_auto_20200315_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='TEAM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormApp.TEAM'),
        ),
        migrations.AlterField(
            model_name='team',
            name='COLOR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormApp.COLOR'),
        ),
        migrations.AlterField(
            model_name='team',
            name='STATE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ormApp.STATE'),
        ),
    ]
