# Generated by Django 2.2 on 2020-03-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormApp', '0003_auto_20200315_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='UNIFORM_ID',
            new_name='UNIFORM_NUM',
        ),
    ]
