# Generated by Django 2.2 on 2020-03-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormApp', '0004_auto_20200315_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='COLOR_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='PLAYER_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='STATE_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='TEAM_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
