# Generated by Django 2.2 on 2020-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormApp', '0005_auto_20200316_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='COLOR_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='PLAYER_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='STATE_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='TEAM_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
